import { getEncryptedCookie } from './getCookies.js';

/**
 |==================================|
 | @function getPageResponseHeaders
 |
 | Generates secure, SEO-controlled and cache-revalidation HTTP response headers
 | for all application pages.
 |
 | For now, pages are marked “noindex, follow”. On publication, change the
 | X-Robots-Tag to “index, follow”.
 | Every request must revalidate: no stale caching at browser or CDN.
 |
 | @param {string} lang   – Content-Language (e.g. "fi", "en")
 | @param {string} nonce  – CSP nonce for inline <script> and <style>
 | @returns {Record<string,string>}  HTTP headers object
 |
 */
export default async function getPageResponseHeaders(lang, nonce, visibility, env) {
	const sessionVerifer = await env.SESSION_VERIFIER.get();
	const cookie = await getEncryptedCookie('SESSION_VERIFIER', sessionVerifer, env, 0);
	const robotsTag = `${visibility}, follow`;
	const cacheControl = 'public, max-age=60, must-revalidate';
	const vary = 'Accept-Encoding, Accept-Language';

	return {
		// CONTENT METADATA
		'Content-Type': 'text/html; charset=utf-8',
		'Content-Language': lang,

		// SECURITY
		'Content-Security-Policy':
			`default-src 'self'; base-uri 'none'; form-action 'self'; ` +
			`script-src 'self' https://challenges.cloudflare.com 'nonce-${nonce}'; ` +
			`style-src 'self' 'nonce-${nonce}'; ` +
			`img-src 'self' data: https://assets.vorte.app; font-src 'self' https://assets.vorte.app; ` +
			`connect-src 'self' https://challenges.cloudflare.com; frame-src https://challenges.cloudflare.com; frame-ancestors 'none'; object-src 'none';`,
		'X-Content-Type-Options': 'nosniff',
		'X-Frame-Options': 'DENY',
		'X-XSS-Protection': '0',
		'Permissions-Policy': 'geolocation=(), microphone=(), camera=(), payment=(), usb=()',
		'Referrer-Policy': 'strict-origin-when-cross-origin',
		'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
		'Cross-Origin-Embedder-Policy': 'require-corp',
		'Cross-Origin-Opener-Policy': 'same-origin',
		'Cross-Origin-Resource-Policy': 'same-origin',
		'X-UA-Compatible': 'IE=edge',

		// COOKIE
		'Set-Cookie': cookie,

		// SEO
		'X-Robots-Tag': robotsTag,

		// CACHING
		'Cache-Control': cacheControl,
		ETag: '"AUTOGENERATED_IF_NEEDED"',
		Vary: vary,
	};
}
